# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: sanjorgek/jflex:mvn


    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          working_directory: Practicas/Practica_2
          command: mvn compile
      - run:
          working_directory: Practicas/Practica_2
          command: mvn exec:java -Dexec.mainClass="testmaven.Test" < src/main/resources/test_ejer1.txt
      - run:
          working_directory: Proyectos/Proyecto_1
          command: mvn compile
      - run:
          working_directory: Proyectos/Proyecto_1
          command: mvn exec:java -Dexec.mainClass="lexico.Test"
